---
apiVersion: v1
kind: Service
metadata:
  name: productdb 
  namespace: buttercup-store
  labels:
    app: buttercup-store
    tier: db
spec:
  type: LoadBalancer
  selector:
    name:productdb 
    tier: db
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
