---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  labels:
    name: cartservice
  namespace: buttercup-store
spec:
  ports:
    # the port that this service should serve on
  - port: 4201
    targetPort: 4201
  selector:
    name: cartservice






#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: productdb
#  namespace: buttercup-store
#  labels:
#    app: buttercup-store
#    tier: db
#spec:
#  type: LoadBalancer
#  selector:
#    name:productdb
#    tier: db
#  ports:
#    - name: mysql
#      port: 3306
#      targetPort: 3306
