#
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: webfrontend
#  labels:
#    name: webfrontend
#  namespace: buttercup-store
#spec:
#  ports:
#    # the port that this service should serve on
#  - port: 8088
#    targetPort: 8088
#  selector:
#    name: webfrontend


---
apiVersion: v1
kind: Service
metadata:
  name: webfrontend 
  namespace: buttercup-store
  labels:
    app: buttercup-store
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    name: webfrontend
  ports:
    - name: webfrontend
      port: 8088
      targetPort: 8088
