name: Docker Image CI

on:
  release:
    types: [published]
    branches: [ master ]

jobs:

  admin_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/buttercup_store/buttercup_store/admin_frontend
        
    steps:
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: derkkila/admin_frontend
        tags: latest
        tag_with_sha: true
